### ISSUE TITLE
Open RE and DS

### ISSUE THREAD

**Issue by wjczf123** [Lfc1993/EI_ORE#1]
This is a very interesting work. But i am not familiar with open RE. It is seems that open RE is a unsupervised task. But you writes that 'This process (E → X ←C) can be conducted through DS.' Why DS works here? Is there a connection between open RE and DS?

**Comment by Lfc1993** [comment]
Thanks for your attention to our work. OpenRE is indeed an unsupervised task. However, the datasets used by current OpenRE methods are collected through distant supervision (or other strategies). Though the OpenRE methods do not utilize the relation label from distant supervision, the generated instances in dataset are definitely effected by the entity pair E and context C of the prototypical instance.

**Comment by wjczf123** [comment]
I know. It is essentially a deviation of the dataset, although labels are not used?

**Comment by Lfc1993** [comment]
To some extent, it could be said so.

**Comment by wjczf123** [comment]
OK. Thank you very much.

**Comment by Lfc1993** [comment]
you're welcome :-)
